// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4pDzqB9Nkoi_FLP2H287MZzbEcKuzU20',
    appId: '1:412727984695:web:70555da5360418b5bb35b2',
    messagingSenderId: '412727984695',
    projectId: 'music-player-8479b',
    authDomain: 'music-player-8479b.firebaseapp.com',
    storageBucket: 'music-player-8479b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8q_PWK7Bnj5KEhtG8dKnszdc5cuGjXk',
    appId: '1:412727984695:android:955a29dc13299bbcbb35b2',
    messagingSenderId: '412727984695',
    projectId: 'music-player-8479b',
    storageBucket: 'music-player-8479b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqEIc3JHc8yTgZjub8HobR8tsjQt2Z89Y',
    appId: '1:412727984695:ios:275a5c7329628672bb35b2',
    messagingSenderId: '412727984695',
    projectId: 'music-player-8479b',
    storageBucket: 'music-player-8479b.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayer',
  );
}
